### PR TITLE
Add Arabic translation

### LINKED ISSUE #11: Arabic Translation
i will provide you Arabic translation string.xml file soon

### PR DESCRIPTION
**Pull request by LouisCAD**
The translation is from @mahmooddagga
Fixes #11

### CODE REVIEW

**Comment by ZieIony** [comment]
Thank you very much!

**Comment by LouisCAD** [comment]
@ZieIony 
You're welcome!
BTW, why don't you push the library on jcenter?

**Comment by ZieIony** [comment]
1. This library is mostly updated by people like you, so it's easier to just merge a pull request and update a jitPack reference (you know jitPack, right? Very useful tool).
2. It's pretty large with Joda Time dependency, which makes it less nice for some users.
3. There's a native, Android class for creating natural date formatting. I'm not very familiar with it, but it may potentially be easier to use.

As this library is pretty stable and has a bunch of users, maybe I should start thinking about Maven.

**Comment by LouisCAD** [comment]
1.~~The [instructions on jitpack](https://jitpack.io/#ZieIony/NaturalDateFormat) are not very useful as there is no GitHub release. I mean, will this snippet:~~

``` groovy
dependencies {
    compile 'com.github.User:Repo:Tag'
}
```

~~really work?~~
**UPDATE** jitpack javascript didn't show the dependency properly, but it seems to be fixed now. Adding GitHub releases and optionaly deploying to jcenter would help though, so we can have predictable versioned builds.
2.This should be written in the README as it can increase the app size. Which Joda-Time version are you using? The one optimized for Android? Anyway, I think it doesn't have much to do with jcenter over jitpack
3.You mean `DateUtils`?

Bonus: Maven is more complicated than jcenter from what I read, but I can help you make releasing to jcenter just a gradle task to run when you want.

**Comment by LouisCAD** [comment]
I edit my comment above

**Pull request merged**
